name: Release

on:
  workflow_dispatch:

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0
          ref: main
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
      - name: Maven Release version and Build
        run: |
          mvn versions:set -DremoveSnapshot
          mvn clean install
          VERSION=$(mvn -N -Dexec.executable=echo -Dexec.args='${project.version}' exec:exec -q -DforceStdout)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Github Release
        uses: softprops/action-gh-release@v2
        with:
          generated_release_notes: true
          tag_name: ${{ env.VERSION }}
          files: |
            target/app/lighter.jar
      - name: Bump version
        run: |
          mvn pull
          mvn versions:set -DnextSnapshot=true
          git config user.email "actions@github.com"
          git config user.name "Automatic releaser workflow"
          git add pom.xml
          git commit -m "chore: bump version to next snapshot"
          git push
